-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.campaignstatus
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    status character varying(100) COLLATE pg_catalog."default",
    campaign_id uuid,
    updated_date date DEFAULT CURRENT_DATE,
    CONSTRAINT campaignstatus_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vehiclecampaign
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    campaign_name character varying(100) COLLATE pg_catalog."default",
    vehicle_id uuid,
    software_version character varying COLLATE pg_catalog."default",
    created_date timestamp with time zone NOT NULL DEFAULT now(),
    start_time timestamp with time zone NOT NULL DEFAULT now(),
    end_time timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT vehiclecampaign_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.vehicles
(
    id uuid NOT NULL DEFAULT uuid_generate_v4(),
    vin character varying(17) COLLATE pg_catalog."default",
    maufacturer character varying(100) COLLATE pg_catalog."default",
    model character varying(100) COLLATE pg_catalog."default",
    make character varying(100) COLLATE pg_catalog."default",
    registration_date date DEFAULT CURRENT_DATE,
    manufactured_date date DEFAULT CURRENT_DATE,
    tenant_id uuid DEFAULT uuid_generate_v4(),
    region character varying(100) COLLATE pg_catalog."default",
    CONSTRAINT vehicles_pkey PRIMARY KEY (id),
    CONSTRAINT vehicle_unique UNIQUE (id, vin)
);

ALTER TABLE IF EXISTS public.campaignstatus
    ADD CONSTRAINT fk_campaign FOREIGN KEY (campaign_id)
    REFERENCES public.vehiclecampaign (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.vehiclecampaign
    ADD CONSTRAINT fk_vehicle_id FOREIGN KEY (vehicle_id)
    REFERENCES public.vehicles (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;